Enabled: true
SubscriptionEndCheckTicks: 100

#yaml mysql
DataProvider: yaml

DataFile: "data.yml"
Mysql:
  Ip: '135.181.169.114'
  User: '2com9'
  Password: 'LS=z3LuCEXD^6wYt'
  Database: 'WellMinedWhiteList'
  Table: 'WellMinedWhiteListTable'

Messages:
  Kick:
    Connecting: '&bВы не в вайтлисте!'
    WhileConnected: '&bВаша подписка закончилась!'
  NoPermission: 'Недостаточно прав.'
  CheckMessageFormat: 'Ваша подписка: %WMWhiteList_subscription_status%'
  WhiteListStatuses:
    Enabled: '&c&lвключен'
    Disabled: '&a&lвыключен'
  DataBase:
    PlayerUndefined: 'Игрок не найден'
    SubscribeNeverEnd: 'никогда не закончится.'
    SubscribeEnd: 'уже закончилась.'