Enabled: true
SubscriptionEndCheckTicks: 100

#yaml mysql
DataProvider: yaml

DataFile: "data.yml"
Mysql:
  Ip: 111.222.333.444
  User: "root"
  Password: "pass"
  Database: "WhiteListDB"
  Table: "WhiteListTable"

Messages:
  Kick:
    Connecting: "&bВы не в вайтлисте!"
    WhileConnected: "&bВаша подписка закончилась!"
  NoPermission: "Недостаточно прав."
  CheckMessageFormat: "Ваша подписка: %WMWhiteList_subscription_status%"
  WhiteListStatuses:
    Enabled: "&c&lвключен"
    Disabled: "&a&lвыключен"
  DataBase:
    PlayerUndefined: "Игрок не найден"
    SubscribeNeverEnd: "никогда не закончится."
    SubscribeEnd: "уже закончилась."