Enabled: true
SubscriptionEndCheckTicks: 100

#yaml mysql
DataProvider: yaml

DataFile: "data.yml"
Mysql:
  Ip: 111.222.333.444
  User: "root"
  Password: "pass"
  Database: "WhiteListDB"
  Table: "WhiteListTable"
  #optional
  Port: 3306
  UseSsl: false
  UseUnicode: true
  AutoReconnect: true
  FailOverReadOnly: false
  MaxReconnects: 2

Translation: "en.yml"

DurationFormat: "&bdd 'days' &cHH 'hours' &emm 'minutes' &ass 'seconds'"