Enabled: true
SubscriptionEndCheckTicks: 100

#yaml mysql
DataProvider: yaml

DataFile: "data.yml"
Mysql:
  Ip: '135.181.169.114'
  User: '2com9'
  Password: 'LS=z3LuCEXD^6wYt'
  Database: 'WellMinedWhiteList'
  Table: 'WellMinedWhiteListTable'

Messages:
  Kick:
    Connecting: '&bВы не в вайтлисте!                                           &fПопасть в вайт лист: &bhttps://wellmined.trademc.org/ &f            Или в дискорде: &bhttps://discord.gg/swg8TqXYxz'
    WhileConnected: '&bВаша подписка закончилась! &fПродлить: https://wellmined.trademc.org/'
  NoPermission: 'Недостаточно прав.'
  CheckMessageFormat: 'Ваша подписка: %WMWhiteList_subscription_status%'
  WhiteListStatuses:
    Enabled: '&c&lвключен'
    Disabled: '&a&lвыключен'
  UsageMessages:
    All:
      - ''
    SimpleUsers:
      - ''
  DataBase:
    PlayerUndefined: 'Игрок не найден'
    SubscribeNeverEnd: 'никогда не закончится.'
    SubscribeEnd: 'уже закончилась.'